### PR TITLE
some minor changes

### LINKED ISSUE #4: Separate into .h file and .cpp file
It seems the current implementation is in the .h file. This is causing issue when I need to include the Dictionary.h file in a class header, which results in the implementation get compiled multiple times in the project and linker complains about the duplicate implementations found in multiple cpp files that include the header file.

Is it possible to separate out the implementation into .cpp file?

### PR DESCRIPTION
**Pull request by vortigont**
- Moved all declarations into separate .h's (fix #4)
 - pass String's as refs to avoid extra copy
 - overload for jload() from char*

### CODE REVIEW

**Comment by arkhipenko** [comment]
Thank you for your help! I will test and merge into master upon successful testing.

**Comment by vortigont** [comment]
@arkhipenko pls, discard my PR, I've found some issues with NodeArray operation when dict created as *dict. Also I've never tested compression/PSRAM opst, looks like it might need some changes to support it. I'm working on a completely new approach currently.
Sorry for the noise.

**Comment by arkhipenko** [comment]
ok. thanks for letting me know. I like the String& changes though - will keep them. 
It maybe better to merge the two .h files into one and then split?

**Comment by vortigont** [comment]
Something is definitely wrong here. Splitting .h files looks pretty simple, not sure if its the real cause, but I do have issues with declaring Dictionary as a class member.

Declaring a Class like this
```
Class Myclass{
  Dictionary cfg;
  std::unordered_map<std::string, buttonCallback> section_handle;
}
```

kills section_handle,

Declaring a Class like this
```
Class Myclass{
  Dictionary cfg;
  AsyncWebServer server;
  AsyncWebSocket ws;
}
```
kills WebServer. Whatever classmeber comes after Dictionary either malfunctioned or results in mcu crash.
And I can't even test your master version, because I can't include a single .h file into my project.
What's the way you usually use it? A single object in a main.ino file? 
What I'm doing is I created an empty dict.cpp with a single line
#include <Dictionary.h>
and in my other MyClass.h header file I use
#include <DictionaryDeclarations.h>

**Comment by arkhipenko** [comment]
I have never used Dictionary in a class like you did.
I usually use one or several in my INOs, both like a static object (before `setup()`)  and dynamically created on the heap:

```
// dictionary containing configuration lines 
Dictionary* d_ptr = NULL;
...
  d_ptr = new Dictionary();
  if ( !d_ptr ) reportError(ERR_MEM, 20401);
  Dictionary& d = *d_ptr;
```

I just ran a test on esp8266 working with 400 key value pairs performing 3000 random lookups
No memory leaks reported:

```
Heap (start): 41712
Pre-populating the dictionary
Heap (prepop): 6560
Measuring lookup base loop
Heap (base): 6560
Measuring lookup actual loop
Heap (lookup): 6560
Measuring delete base loop
Measuring delete actual loop
Heap (delete): 40048

Current size = 0
Current count = 0

Lookup duration: 116025 micros, rate=38.67 micros/lookup
Delete duration: 30395 micros, rate=75.99 micros/delete
Heap (destroy): 41712
```

**Comment by vortigont** [comment]
Thanks for your comments. My idea is to use Dictionary in library class not in the main project. Than I can reuse that library in other projects, that's why I'm trying hard to split .h file.
I will try to narrow down those issues myself, but pls, take a look into this PR when you have time, I might have missed something.

**Pull request merged**
